In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("enterprise_supply_chain_dataset.csv")
df.head()

,Order_ID,Order_Date,Delivery_Date,Region,Country,City,Product_Name,Supplier_Name,Warehouse,Order_Quantity,...,Reorder_Level,Stockout_Flag,Defect_Rate,Order_Status,Delivery_Days,Profit_Margin,Delay_Flag,Order_Month,Order_Year,Inventory_Status
0,ORD00001,2025-10-16,2025-10-19,West,India,Hyderabad,Laptop,Supplier B,Warehouse 1,48,...,119,No,1.27,Delivered,3,50.609823,On Time,October,2025,Sufficient
1,ORD00002,2025-06-01,2025-06-12,North,USA,Bangalore,Tablet,Supplier C,Warehouse 1,36,...,125,No,3.65,Cancelled,11,29.516053,Delayed,June,2025,Sufficient
2,ORD00003,2024-08-08,2024-08-24,North,UAE,Hyderabad,Printer,Supplier C,Warehouse 3,7,...,55,No,3.08,In Transit,16,42.811666,Delayed,August,2024,Sufficient
3,ORD00004,2025-09-25,2025-10-12,North,UAE,Delhi,Monitor,Supplier C,Warehouse 1,37,...,60,No,2.21,Pending,17,49.284140,Delayed,September,2025,Sufficient
4,ORD00005,2025-01-14,2025-01-22,South,UAE,Bangalore,Tablet,Supplier B,Warehouse 3,43,...,71,No,1.04,Pending,8,30.177191,On Time,January,2025,Sufficient

In [4]:
df.shape

(1000, 27)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            1000 non-null   object
 1   Order_Date          1000 non-null   object
 2   Delivery_Date       1000 non-null   object
 3   Region              1000 non-null   object
 4   Country             1000 non-null   object
 5   City                1000 non-null   object
 6   Product_Name        1000 non-null   object
 7   Supplier_Name       1000 non-null   object
 8   Warehouse           1000 non-null   object
 9   Order_Quantity      1000 non-null   int64
 10  Unit_Price          1000 non-null   int64
 11  Revenue             1000 non-null   int64
 12  Shipping_Cost       1000 non-null   float64
 13  Manufacturing_Cost  1000 non-null   float64
 14  Profit              1000 non-null   float64
 15  Lead_Time_Days      1000 non-null   int64
 16  Inventory_Level     1000 non-null   int64
 17  Reorder_Level       1000 non-null   int64
 18  Stockout_Flag       1000 non-null   object
 19  Defect_Rate         1000 non-null   float64
 20  Order_Status        1000 non-null   object
 21  Delivery_Days       1000 non-null   int64
 22  Profit_Margin       1000 non-null   float64
 23  Delay_Flag          1000 non-null   object
 24  Order_Month         1000 non-null   object
 25  Order_Year          1000 non-null   int64
 26  Inventory_Status    1000 non-null   object
dtypes: float64(5), int64(8), object(14)
memory usage: 211.1+ KB

In [6]:
df.describe()

,Order_Quantity,Unit_Price,Revenue,Shipping_Cost,Manufacturing_Cost,Profit,Lead_Time_Days,Inventory_Level,Reorder_Level,Defect_Rate,Delivery_Days,Profit_Margin,Order_Year
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,25.77700,1027.474000,26534.461000,1971.018530,14468.095600,10095.346870,8.29500,252.216000,102.202000,4.215600,10.86700,37.617990,2024.494000
std,14.69596,540.579083,21906.864487,1824.303613,12276.632709,8890.665825,4.03488,141.479043,29.653677,2.148903,4.41189,8.762958,0.500214
min,1.00000,100.000000,223.000000,20.060000,121.460000,76.110000,2.00000,2.000000,50.000000,0.500000,2.00000,18.377080,2024.000000
25%,12.00000,539.000000,9015.750000,588.885000,4839.990000,3129.340000,5.00000,134.000000,76.750000,2.350000,7.00000,30.561985,2024.000000
50%,25.00000,1016.000000,20107.500000,1407.745000,10776.435000,7612.715000,8.00000,255.000000,104.000000,4.180000,11.00000,37.432600,2024.000000
75%,39.00000,1480.250000,39024.000000,2853.992500,21456.152500,14498.997500,12.00000,373.250000,129.000000,6.052500,14.00000,44.864028,2025.000000
max,50.00000,1990.000000,96187.000000,10500.810000,62863.270000,43775.490000,15.00000,500.000000,150.000000,8.000000,20.00000,56.211463,2025.000000

In [7]:
df.columns

Index(['Order_ID', 'Order_Date', 'Delivery_Date', 'Region', 'Country', 'City',
       'Product_Name', 'Supplier_Name', 'Warehouse', 'Order_Quantity',
       'Unit_Price', 'Revenue', 'Shipping_Cost', 'Manufacturing_Cost',
       'Profit', 'Lead_Time_Days', 'Inventory_Level', 'Reorder_Level',
       'Stockout_Flag', 'Defect_Rate', 'Order_Status', 'Delivery_Days',
       'Profit_Margin', 'Delay_Flag', 'Order_Month', 'Order_Year',
       'Inventory_Status'],
      dtype='object')

In [8]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Delivery_Date         0
Region                0
Country               0
City                  0
Product_Name          0
Supplier_Name         0
Warehouse             0
Order_Quantity        0
Unit_Price            0
Revenue               0
Shipping_Cost         0
Manufacturing_Cost    0
Profit                0
Lead_Time_Days        0
Inventory_Level       0
Reorder_Level         0
Stockout_Flag         0
Defect_Rate           0
Order_Status          0
Delivery_Days         0
Profit_Margin         0
Delay_Flag            0
Order_Month           0
Order_Year            0
Inventory_Status      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"])

In [12]:
df["Delivery_Days"] = (
    df["Delivery_Date"] - df["Order_Date"]
).dt.days

In [12]:
df["Profit_Margin"] = (
    df["Profit"] / df["Revenue"]
) * 100

In [13]:
df["Delay_Flag"] = np.where(
    df["Delivery_Days"] > 10,
    "Delayed",
    "On Time"
)

In [14]:
df["Order_Month"] = df["Order_Date"].dt.month_name()

In [15]:
df["Order_Year"] = df["Order_Date"].dt.year

In [16]:
df["Inventory_Status"] = np.where(
    df["Inventory_Level"] < df["Reorder_Level"],
    "Low Stock",
    "Sufficient"
)

In [17]:
df["Revenue"].sum()

np.int64(26534461)

In [18]:
df["Profit"].sum()

np.float64(10095346.870000001)

In [19]:
df["Lead_Time_Days"].mean()

np.float64(8.295)

In [20]:
df["Stockout_Flag"].value_counts()

Stockout_Flag
No     811
Yes    189
Name: count, dtype: int64

In [21]:
df["Order_Status"].value_counts()

Order_Status
In Transit    268
Delivered     260
Cancelled     249
Pending       223
Name: count, dtype: int64

In [22]:
df.groupby("Supplier_Name")["Profit"].sum()

Supplier_Name
Supplier A    2748947.34
Supplier B    2245179.34
Supplier C    2496043.38
Supplier D    2605176.81
Name: Profit, dtype: float64

In [23]:
df.groupby("Product_Name")["Revenue"].sum().sort_values(ascending=False)

Product_Name
Monitor     5113486
Tablet      4564216
Laptop      4379097
Phone       4349710
Keyboard    4257047
Printer     3870905
Name: Revenue, dtype: int64

In [24]:
df.groupby("Warehouse")["Revenue"].sum()

Warehouse
Warehouse 1    8648493
Warehouse 2    8533084
Warehouse 3    9352884
Name: Revenue, dtype: int64

In [25]:
df.to_csv("cleaned_supply_chain_data.csv", index=False)